name = "VulkanGen"
uuid = "a1e12450-decb-4c3e-a000-968e74262140"
authors = ["Cédric BELMANT"]
version = "0.1.0"

[deps]
VulkanCore = "16167f82-ea26-5cba-b1de-ed6fd5e30a11"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
